kind: ConfigMap
apiVersion: v1
metadata:
  name: devops-blue-configmap                                   # configmap-name
immutable: false    # optional, if set to true then data cannot be changed later
data:
  microservice.name: "blue"                                     # configmap-key-A
